### ISSUE TITLE
[Bug] NavBallTextureChangerUpdated not showing up in Newest CKAN

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8398]
Two issues here:

First, and most important:
I added NavBallTextureChangerUpdated last night, it's referencing the Github install for downloads.

I waited overnight, it still isn't visible at all in CKAN.exe.  Not sure if it's relevant, CKAN.exe was updated this morning.  I set the filter to "All", it didn't show

The .version has a KSP_MIN_VERSION of 1.8.0, when I look at the generated meta data, I don't see any game version info at all

(see below comment) Second, and lesser, I see in CKAN.exe that there is an older (much older) version from xEvilReeperx.  I'd like to add that as a conflict, but I can't find the right value to add as an exclusion

Edit:  I just found the correct identifier for the older one, I'll update my .netkan file with it

**Comment by linuxgurugamer** [comment]
I saw an issue in the Actions, the Inflate netkans # 8.
The issue with the remote version file has been resolved, but that was a warning, not an error.  The error is with OPTSpacePlaneMain (????) which has nothing to do with this mod

**Comment by linuxgurugamer** [comment]
I also just added the mod to SpaceDock, and updated the netkan to reflect that, hoping that helps

**Comment by linuxgurugamer** [comment]
The update to using Spacedock seemed to solve the problem, it's now available.  But curious why it wasn't working with Github.

**Comment by HebaruSan** [comment]
The bot was/is gummed up, unrelated to this mod:

![image](https://user-images.githubusercontent.com/1559108/110245725-1144af00-7f2a-11eb-9529-3e78345c45da.png)

![image](https://user-images.githubusercontent.com/1559108/110245754-1efa3480-7f2a-11eb-84c4-36dc39ac4d38.png)

It coincidentally managed to complete a pass when you moved this mod to SpaceDock; that didn't solve it, it just happened at the same time. We're trying to contact @techman83 to look into what the problem is.
