### ISSUE TITLE
[Bug]A Metadata issues

### ISSUE THREAD

**Issue by ZCM8848** [KSP-CKAN/NetKAN#8425]
Background
----------
* Operating System: windows10 home edition（x64）
* CKAN Version: v1.30.0
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

no

Problem
-------
**Describe the bug**
Can not install "Tundra Exploration - Stockalike Dragon V2 and Falcon 9 3.3.0 (spacedock.info, 130.2 MiB)"

**Steps to reproduce**
When it finishes downloading the mod, an error window will appear.

**Screenshots (if applicable)**
![CCAGG0L${5H0Z)6$CPZAB`T(1)](https://user-images.githubusercontent.com/68009258/111859880-06a10580-897f-11eb-8f75-2c6d066dcf9e.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
Same error as #8315. Unfortunately that issue has been closed by the reporter with a very unhelpful comment.

Interestingly, this time it's again with a Chinese locale.

@ZCM8848 can you try downloading and extracting the file manually? Does that work?
https://spacedock.info/mod/223/Tundra%20Exploration%20-%20Stockalike%20Dragon%20V2%20and%20Falcon%209/download/3.3.0

**Comment by ZCM8848** [comment]
I tried to download the zip file separately before, and when decompressing it, the winrar software did not report any errors.seems that everything is OK.But the game cannot load the mod.

**Comment by ZCM8848** [comment]
I tried to download the zip file separately before, and when decompressing it, the winrar software did not report any errors. it looks everything is OK. But the game cannot load the mod.
I also tried to install this mod by CKAN manually. ckan showed no error.but the mod just wasn't there.

**Comment by DasSkelett** [comment]
Thanks. Can you try again with this debug build of ckan.exe?
It is compiled with a newer version of `SharpZipLib`, the library we use to handle and extract zip files.
With a lot of luck this is a bug in that library and already solved in newer versions.
[ckan.zip](https://github.com/KSP-CKAN/NetKAN/files/6177675/ckan.zip)

**Comment by ZCM8848** [comment]
@DasSkelett 
Thanks for your sharing, I received the debug build of CKAN. And I had just use it to install that mod
But the same thing happened again......
![屏幕截图 2021-03-22 184207](https://user-images.githubusercontent.com/68009258/111978484-e61fa980-8b3e-11eb-9352-c1add3fc3513.png)

**Comment by DasSkelett** [comment]
> Thanks for your sharing, I received the debug build of CKAN. And I had just use it to install that mod
> But the same thing happened again......

That doesn't look like you used the debug build, it shows "v1.30.0" in the title bar, which is the version number of the ckan.exe from the release. My debug build should show v1.30.1.
Did you accidentally mix up the two files? Can you try again, this time making sure you use the debug build I uploaded?

**Comment by ZCM8848** [comment]
> > Thanks for your sharing, I received the debug build of CKAN. And I had just use it to install that mod
> > But the same thing happened again......
> 
> That doesn't look like you used the debug build, it shows "v1.30.0" in the title bar, which is the version number of the ckan.exe from the release. My debug build should show v1.30.1.
> Did you accidentally mix up the two files? Can you try again, this time making sure you use the debug build I uploaded?

Sorry about that. I accidentally mix up the two files😅
In CKAN v1.30.1, it still shows the same situation.
![屏幕截图 2021-03-22 224907](https://user-images.githubusercontent.com/68009258/112067237-b2766b00-8ba2-11eb-8e2e-25f4b4cea5a0.png
This also happens even I switch the language of CKAN to english

**Comment by HebaruSan** [comment]
Might as well include here that netkan has been emitting the same error for certain mods:

![image](https://user-images.githubusercontent.com/1559108/114279738-b2d98780-9a25-11eb-9cab-bed0658c6204.png)

@DasSkelett traced this to a setting in SharpZipLib that controls whether filenames are interpreted in Unicode, which is off by default (!!). Hopefully enabling that setting will solve both problems.
